Update README.md
SubjectiveLabs/SubjectiveAssembly pull request #106
Opened 2023-10-26 01:44 UTC by dcndr

2023-10-26 04:23 UTC, circles-png requested changes
write some stuff about the api endpoints here or in the wiki

2023-10-26 04:23 UTC, circles-png commented on README.md
> +4. Connect to the server with Subjective by inputting the host link of Assembly, this would be the server's local IP address, or if the server is on the web, it's web address.
inputting is not a very good word
the first comma doesnt make sense
`it's` is wrong

2023-11-04 02:09 UTC, dcndr commented on README.md
> +4. Connect to the server with Subjective by inputting the host link of Assembly, this would be the server's local IP address, or if the server is on the web, it's web address.
this is why im failing english

2023-11-04 02:41 UTC, circles-png commented on README.md
> +4. Connect to the server with Subjective by inputting the host link of Assembly, this would be the server's local IP address, or if the server is on the web, it's web address.
couldnt be me

2023-11-04 02:44 UTC, circles-png approved these changes

2023-11-04 05:40 UTC, merged